### ISSUE TITLE
[1.12]Suggestion: Add further energy compatability to EMP

### ISSUE THREAD

**Issue by ghost** [BuiltBrokenModding/ICBM-Classic#118]
I suggest that the EMP explosive can also drain other kinds of energy from for example IC2 (EU) ,mekanism (MJ) ,thermal foundation (RF) etc.

**Comment by DarkGuardsman** [comment]
Already on the work list but will always be limited. Most mods do not support quick draining of tiles. Especially since most mods picked up a limited input/output model from thermal expansion. Which has made it difficult to remove power without impacting performance. 

I am considering making a pull request to forge to help solve the problem. As most mods do use Forge Energy which could implement a setEnergy(value) method. I already talked to King about this for RF but was told no. 

IC2 and Mek should be possible. It just going to be RF and FE supported machine that will not work perfectly. ICBM-2 in 1.7.10 has a few workarounds for this that I could apply.
