### ISSUE TITLE
Recipes issues

### ISSUE THREAD

**Issue by LemADEC** [BuiltBrokenModding/ICBM-Classic#12]
As of 1.7.10-2.15.1b33, the following recipes issues exit:
- [x] Camouflage recipe is missing "circuitBasic" in center (that ore dictionnary name seems to be valid for both IC2 and Mekanism)
- [x] "ingotSteel" should be used instead of iron in Reinforced concrete and Reinforced glass recipes
- [x] Rejuvenation explosive recipe is using 4 saddles where it should use 4 clocks
- [x] Ender explosive recipe used to have 6 endstone + 2 ender pears in 1.5.2, now it's 8 ender pearls. Is it intended?
- [x] Antimatter explosive has no recipe
- [ ] Some recipes only supports Mekanism, here are some proposals for IC2, TE and EnderIO:
* Energy tablets in EMP explosive recipe could be IC2 Advanced RE-battery, TE potato battery and EnderIO double-layer capacitor
* Battery box in EMP tower could be IC2 CESU, TE Redstone energy cell and EnderIO Capacitor bank
* Elite circuit in EMP tower, Launcher platform/control panel T3, Laser designator could be Nether skull heads

**Comment by DarkGuardsman** [comment]
I made camouflage cheaper in 1.6.4 as it made no sense to require electronics for a primitive block.

I'll fix the rest and implement additional recipes as I go though the UniversalRecipe system. Which is most likely why iron is being used in some recipes. Since it is ore-dictionary driven and uses replacements if it can't find anything.
