### ISSUE TITLE
[1.12.2] Possible Spongeforge incompatability

### ISSUE THREAD

**Issue by ghost** [BuiltBrokenModding/ICBM-Classic#120]
ICBM- Classic version: ICBM - Classic 1.12.2-3.0.0b22 build 22 for 1.12.2
Please refer to this issue for everything https://github.com/SpongePowered/SpongeForge/issues/2090

**Comment by ghost** [comment]
And one explosive runs into a multithreading issue(thermobaric) https://pastebin.com/B7Md8zpq
Do note that even this explosive works when spongeforge ain't present

**Comment by DarkGuardsman** [comment]
Threaded explosives include Sonic, Rot, Nuclear (Large thread), and AntiGrav (small thread)

I've added a try-catch around the postcode and a null check if the thread failed to run. The first should catch any errors. While the second should let me know if the thread itself is the issue. If it turns out the world is null then something is fishy. As the world shouldn't be able to go null and still have the blast run.
