### ISSUE TITLE
Concrete/compact concrete/reinforced concrete same blast resistance 

### ISSUE THREAD

**Issue by norm1000100** [BuiltBrokenModding/ICBM-Classic#139]
When testing on superflat, encasing a nuke in any of these blocks produces the same blast pattern, implying  the same blast resistance.

**Comment by DarkGuardsman** [comment]
Neglected to add the resistance back when updating to 1.12

Also as a note, use blast patterns does not always work. As even a small difference can go unnoticed in simple tests.
![screenshot 2018-07-06 20 50 37](https://user-images.githubusercontent.com/1477330/42405080-8f55d1ca-815e-11e8-83b0-89841db15ad4.png)
Example, tier 2 & 3 concrete have the same blast pattern due to explosive running of out energy.
