### ISSUE TITLE
[1.12] Various issues

### ISSUE THREAD

**Issue by xenon-difluoride** [BuiltBrokenModding/ICBM-Classic#157]
Found on an older version, some of these might be outdated
* EMP explosives are uncraftable
* Sulfur isnt oredictionaried and if another mod (read: TE) adds sulfur then ICBM sulfur doesnt drop and is unobtainable, making anything that needs incindiary explosives unobtainable too (thermo, debil, nukes, RM, AM)
* You can't seem to see things on the radar
* Homing missiles are uncraftable
* Cluster missiles are uncraftable

**Comment by DarkGuardsman** [comment]
You're using the latest alpha right? As Sulfur is ore dictionaried with other mods. This was a bug reported recently and has been fixed.

Homing and cluster are intentionally uncraftable until they can be finished.

**Comment by CplPibald** [comment]
Wanted to comment on this, as I am experiencing the sulfur issue above.

Sulfur is oredicted, which means ICBM sulfur can be used in other mods' recipes that uses `ore:dustSulfur`.  The problem above (confirmed in **v3.1-0b43**) is that all of the ICBM recipes call for `icbmclassic:sulfurdust` instead of the oredicted version.  See [incendiary.json](https://github.com/BuiltBrokenModding/ICBM-Classic/blob/1.12/src/main/resources/assets/icbmclassic/recipes/explosives/incendiary.json) for an example.

This means that oredicted sulfur (such as TE) cannot be used in ICBM recipes.  If you turn off ICBM sulfur drops from creepers, there is no way to get the ICBM sulfur item, and therefore no way to craft the ICBM recipes that use sulfur.

To fix this, modify all of the mod's recipes that use the ingredient `icbmclassic:sulfurdust` to use `ore:dustSulfur` instead.

**Comment by DarkGuardsman** [comment]
As I said before its been fixed https://github.com/BuiltBrokenModding/ICBM-Classic/blob/1.12-dev/src/main/resources/assets/icbmclassic/recipes/explosives/incendiary.json#L16 just no new builds have been released due to gradle script issues.

**Comment by xJon** [comment]
EMP explosives still seem uncraftable using the latest alpha build, not sure if that's intentional or not
