### ISSUE TITLE
[1.12] Missiles can get stuck in unloaded chunks (right after launchpad launch)

### ISSUE THREAD

**Issue by Nethermore** [BuiltBrokenModding/ICBM-Classic#171]
I'm running the most recent version on 1.12.2 and if I fire a missile over too far of a distance about 80% of the time it gets stuck.

**Comment by DarkGuardsman** [comment]
@GHXX can you take a look at this issue

**Comment by GHXX** [comment]
@Nethermore The latest curse-build?

**Comment by Nethermore** [comment]
Yea from Sept 13th

**Comment by GHXX** [comment]
Okay, ill look into it tomorrow, how did you launch the missile? did you use the handheld rocket launcher?

**Comment by Nethermore** [comment]
It happens with both handheld launchers and the T3 platform. I haven't tried with T1 or T2

Also, if I ride the missile it works just fine.

**Comment by GHXX** [comment]
It appears that this only happens when missiles are not loaded. When you launch missiles using the Launchpads (T1,T2,T3) they are simulated and thus dont depend on the chunks being loaded, because the missile is removed, simulated and then added back into the world at the target location. The target chunk is force-loaded, meaning the missile will impact properly.
If you launch a missile and the missile becomes unloaded before it was removed (this takes around 10 to 15 seconds usually which is the time it takes to fly up pretty far) then it gets stuck until the chunk is loaded again. since your base is usually chunk loaded this shouldnt be an issue. You could chunkload the launchpad and set the lock-height to a large value (255 or so) to make sure it flies straight up.

The handheld rocketlauncher, to me is designed for close-ish combat action and thus the chunks should be loaded at all times.

Riding the missile loads the surrounding chunks and thus gets rid of the issue. Loading all chunks a missile is travelling through isn't very efficient performance-wise though. 

Chunkloading launchpads is something we might look at in the future, but its not a major issue, at least not right now, as its actually possible to fire missiles at long ranges (100k+ blocks) without them getting stuck anywhere if the launch is done properly.

**Comment by Nethermore** [comment]
Good to know. Thanks for explaining!

**Comment by johonggnJA** [comment]
> It appears that this only happens when missiles are not loaded. When you launch missiles using the Launchpads (T1,T2,T3) they are simulated and thus dont depend on the chunks being loaded, because the missile is removed, simulated and then added back into the world at the target location. The target chunk is force-loaded, meaning the missile will impact properly.
> If you launch a missile and the missile becomes unloaded before it was removed (this takes around 10 to 15 seconds usually which is the time it takes to fly up pretty far) then it gets stuck until the chunk is loaded again. since your base is usually chunk loaded this shouldnt be an issue. You could chunkload the launchpad and set the lock-height to a large value (255 or so) to make sure it flies straight up.
> 
> The handheld rocketlauncher, to me is designed for close-ish combat action and thus the chunks should be loaded at all times.
> 
> Riding the missile loads the surrounding chunks and thus gets rid of the issue. Loading all chunks a missile is travelling through isn't very efficient performance-wise though.
> 
> Chunkloading launchpads is something we might look at in the future, but its not a major issue, at least not right now, as its actually possible to fire missiles at long ranges (100k+ blocks) without them getting stuck anywhere if the launch is done properly.

Well if 100k blocks is  possible why does it struggle and not load or get stuck at 2400 blocks? I am quite certain I did the launch right as you say but if you would explain what a correct launch process is that would be helpful. Why should I have to load all the chunks if you claim the missle stops being an entity that needs to have chunks loaded. Also I am on 1.7.10 version but have the same issues so.

**Comment by DarkGuardsman** [comment]
1.7.10 version does not have chunk loading nor is it supported.

**Comment by GHXX** [comment]
@johonggnJA this ticket is specifically for 1.12 as shown in the title.
@DarkGuardsman did we even have the missile sim in 1.7.10? Because i dont think so

**Comment by GHXX** [comment]
Will likely need to add chunkloading of the launchpad, or kick it right into simulation if the launchpad is not loaded.
But the rocket launcher will not get loaded, since its for close combat action in my opinion.

**Comment by DarkGuardsman** [comment]
1.7.10 classic version lacked missile sim, thought ICBM 2 had it. Still I want to avoid chunk loading as much as possible due to how hard it is to maintain and keep working.

**Comment by nick3131** [comment]
@DarkGuardsman so just to clarify, because some friends and I are playing now. 1.7.10 does not have the feature where it unloads the missile and loads it at the target? I'm having an issue where the target is 2500 blocks away but the missile tries to fly through all the chunks and is eventually just despawn unless I ride the missile there.

**Comment by GHXX** [comment]
Correct, 1.7.10 does not have the smart missile respawning included.
