### ISSUE TITLE
[1.12.2] b56 Friendly missiles disabled by friendly EMP tower

### ISSUE THREAD

**Issue by PlantDaddy** [BuiltBrokenModding/ICBM-Classic#180]
I have a base that has its perimeter is protected via EMP towers. Inside my base I've created a missile silo with a T3 Launcher and controller. However, whenever I launch a missile from my base to a target, my base protecting EMP towers disable it.

IIRC the old version had the capability of knowing what was friendly and non-friendly for flying missiles. Either way, it would be nice to be able to have a base protected with EMP towers and still be able to launch missiles from the same base.

**Comment by PlantDaddy** [comment]
Maybe a better description would be 'radar stations trigger on friendly launches'?

**Comment by DarkGuardsman** [comment]
Considering I didn't change the code for the EMP tower much since 1.5. Its likely always shot down friendly missiles. The difference is likely that radar towers use to know friend from foe using signal IDs from the launchers. This feature is not in the latest version since we plan to go to an actual FoF system. 

EMP towers will likely never be setup to not kill friendly missiles. This has always been the design from the start. The cost of using the EMP is that it will harm everything. Not just enemy items, blocks, and weapons.

**Comment by PlantDaddy** [comment]
Good to know, thanks for the input!
