### ISSUE TITLE
thermobaric crashes the game

### ISSUE THREAD

**Issue by Redd56** [BuiltBrokenModding/ICBM-Classic#187]
simply put, the thermobaric explosive just crashes the game when it goes off. 
crash report: [https://pastebin.com/TxSK3X26](url)

**Comment by DarkGuardsman** [comment]
Ya that build should not have been released

**Comment by Redd56** [comment]
OOF.avi

**Comment by DarkGuardsman** [comment]
Found the issue, when I was doing the start of the rewrite I changed how blasts set there positions. In doing so I set 

location = newLocation(world(), x, y, z);

the method world() -> location.world(). 

Since location is not set it would null and crash

**Build 62** should be uploaded soon fixing the problem

**Comment by Redd56** [comment]
OOF
