### ISSUE TITLE
Using commands to place explosives ignores metadata

### ISSUE THREAD

**Issue by DaComputerNerd717** [BuiltBrokenModding/ICBM-Classic#247]
When using commands to place explosives, they do not place according to the metadata, and instead always places condensed explosives (metadata 0). As an example, running /setblock ~ ~ ~ icbmclassic:explosives 11 places condensed explosives, not breaching explosives

**Comment by DaComputerNerd717** [comment]
this does not apply with the item. /give gives the right item, for instance.

**Comment by DarkGuardsman** [comment]
Meta for blocks is only used for rotation, the item meta is turned into nbt
data to store the explosive id

**Comment by DaComputerNerd717** [comment]
Interesting, in the creative tab each explosive has its own metadata

**Comment by DarkGuardsman** [comment]
Yep, this is due to the metadata of the **item** being used to track the explosive ID. It makes assigning renders and other logic rather easy. However, when we go to place the **block** we only have 16 metadata values max. Meaning that we can't use it for explosive IDs so instead we store those in the **TileEntity** and **NBT** save. Using the metadata of the block instead to track rotation for the renders. 

When we do the 1.14 update this will change with each explosive getting its own block type (maybe each item version as well). As we will have near infinite block IDs to use for simplifying our logic massively. Likely even removing the need for a TileEntity on most explosives with the exception of Ender which saves a teleport location.

Something that is important to note with Minecraft is that Items and Blocks are not the same thing. It just happens that most mods and even the base game use the metadata to also track the placement metadata of the block. However, there are examples such as doors that don't follow this logic. In which the item is not an ItemBlock but instead a normal item that does a multi-block placement.

**Comment by DaComputerNerd717** [comment]
I understand, I've worked with forge a bit too. A majority of the time I see metadata used, a limit of 16 fits both block and item, like the blocks of metal from Thermal Foundation. Anyways, what is the NBT tag the explosive type data is stored in? What format is it? How would I use, say, /setblock to place a breaching explosive?

**Comment by DarkGuardsman** [comment]
Good question, might have to place a few and dump the NBT to see. As its changed enough in the current code that I don't recall what it use to be before the rewrite started.

**Comment by DaComputerNerd717** [comment]
Two things: Firstly, the tag is called "explosiveID" and contains the number from the metadata. 
Other thing, which I may have to make a new issue for: When using setblock to set like this, the block looks like that explosive, and explodes like that explosive, but anything that identifies blocks and also the vanilla Pick Block function identify it as just condensed explosives. It does not do this with explosives placed down normally, only explosives created using block placing commands.

**Comment by bl4ckscor3** [comment]
That's likely because some NBT data is still missing.

**Comment by DaComputerNerd717** [comment]
I'm not sure what missing data that would be, since when placed only one piece of data was there that identified it. The rest was x, y, z, and an id tag just holding the block id.

**Comment by DarkGuardsman** [comment]
The current version on curse has a few issues with pick block last I recalled. Its been fixed in the rewrite branch but we have not done a new release in over 6 months.
