### ISSUE TITLE
Rejuvenation explosives?

### ISSUE THREAD

**Issue by xJon** [BuiltBrokenModding/ICBM-Classic#284]
I am aware of previous issues, but do you have any plans of bringing them back?
They had a very unique functionality that does not exist in any other form in modded Minecraft today.
Thank you!

**Comment by Redd56** [comment]
They are in the mod

**Comment by DarkGuardsman** [comment]
They were in the mod, the current beta has then but the latest alpha does not. Due to in ability to maintain them they were removed. As almost every MC update they break horribly and take too long to fix. Since they were originally built as an admin tool I saw no point in keeping them. 

That said ICBM is now easier to make addons for so anyone can add them back.

**Comment by Redd56** [comment]
I'll learn some code on them a d add them back as a side project down the line then, or make an admin tools pack later with them

**Comment by DarkGuardsman** [comment]
Admin tools set would be a better option to avoid people abusing regen missiles for ores.

**Comment by xJon** [comment]
It is nice to have a Forge only option, is the thing. Thank you for the info @DarkGuardsman
