### ISSUE TITLE
[1.12] Radar not transmitting redstone.

### ISSUE THREAD

**Issue by gusjdy** [BuiltBrokenModding/ICBM-Classic#294]
Hello, I am trying to use ICBM together with FTB Ultimate Reloaded. When I put a radar an enter its UI it detects nearby missile, nonetheless, it does not output Redstone signal when the missile is in the alarm range or any range. This is to be used with AB missile or EMP tower.

 I can manually deploy the AB though.

**Comment by DarkGuardsman** [comment]
version of MC, the mod, and your setup

**Comment by gusjdy** [comment]
MC Version 1.12
Mod Version ICBM-classic-1.12.2-3.3.0b63.jar
Working in conjunction with FTB Ultimate Reloaded Mods.

Setup: Tier 2 Launcher, AB Missile, Tier 2 control, Radar connected to control through redstone.

**Comment by gusjdy** [comment]
![image](https://user-images.githubusercontent.com/62820327/77838141-fd4fd500-713e-11ea-9af9-8d7329b7a9c3.png)

**Comment by Tommeh1** [comment]
Can verify using custom build until this commit: https://github.com/BuiltBrokenModding/ICBM-Classic/commit/a5d481c486a74b288a0cf4ccf4a12cd963644fce on a server

**Comment by dmitri-mcguckin** [comment]
Just wanted to chime in, I was also having the same issues mentioned above.

Tested on
* ICBM-Classic 1.12.2 v4.0.0b71
* ICBM-Classic 1.12.2 v4.0.1b75

Just a simple creative capacitor next to a radar and shooting chemical missiles around or at the radar does not set it off in either version.

Would love to know if this can get a fix anytime soon because this mod is a central mod to a battleships-like server I'm running with some pals.
