### ISSUE TITLE
Missiles Despawn Mid-flight

### ISSUE THREAD

**Issue by spartainman64** [BuiltBrokenModding/ICBM-Classic#320]
I have a problem where missiles will despawn while in flight. I tested with a friend and missiles seem to despawn after launch when the target is approximately 1,000 blocks away. We tested this using a T3 platform and T3 support. From what I understand the T3 platform has a maximum range of 10,000 blocks by default. Please help.

(For record, I am using the mod on Forge. Minecraft version 1.12.2)

**Comment by GHXX** [comment]
Yes, they do despawn, and its intended that they do.
They travel up, and at some point they despawn and icbm puts them into "simulation mode". Then a timer ticks down, and then the missile is respawned at the target location, where it then will fly down into the target. This is done so that the flight path of the missile does not have to be chunkloaded.

**Comment by spartainman64** [comment]
Ok. But me and my friend recorded that a missile launched at a target exactly 1000 blocks away takes roughly 1:30 minutes to impact. Then  we tried 2000 blocks and it never came. We waited almost 10 minutes. (Using a t3 launcher with t3 supports)

**Comment by DarkGuardsman** [comment]
Likely failed at some point then. If you can check the logs it might note why.

**Comment by GHXX** [comment]
Is there any more info on this? @spartainman64

**Comment by spartainman64** [comment]
I haven't played with the mod in a while. What I know is that with a Tier 3 launch setup with support frames a missile had a approximate range of 1,000 blocks that I could confirm had impacted the target location. Now it's been a while so I'm not 100% for sure but the last time I checked the config file fo the mod, a Tier 3 silo has a maximum range of 10,000 blocks. If you want we can get in touch and I can show you the issue.

**Comment by GHXX** [comment]
Best case scenario would be a list of steps to reproduce the issue with, if you want to get in touch you could join our discord server (https://discord.gg/NsJ4Ccr) and message me about it, or talk about it in the #icbm-classic channel.

**Comment by kolya5544** [comment]
Just had an exact issue of a missile never coming to a destination. It was 200 blocks away, I waited for 10 minutes. T2 panel + T2 launcher, used Thermobaric missile.

**Comment by DarkGuardsman** [comment]
If you could check the logs for any errors or messages saying if it failed to spawn

**Comment by GHXX** [comment]
Is there any news on this? Especially curious about any logs (with all the icbm settings turned on)

**Comment by KeiHasFallen** [comment]
> Yes, they do despawn, and its intended that they do.
> They travel up, and at some point they despawn and icbm puts them into "simulation mode". Then a timer ticks down, and then the missile is respawned at the target location, where it then will fly down into the target. This is done so that the flight path of the missile does not have to be chunkloaded.

Can you make it not despawn?
Also what's the purpose of it despawning?

**Comment by GHXX** [comment]
The point of them despawning is that we dont have to load every chunk the missile travels through, instead we remove the missile from the world, keep track of it, and after the appropriate amount of time, spawn it back in, so that it is like as if it actually flew there, but way more stable, and way more server tick friendly.

**Comment by DarkGuardsman** [comment]
Despawn is likely a poor choice in wording. What actually happens is they phase out of the game map and into a separated data map. They still travel while phased out but are not in the world to prevent spiking CPU usage with short term chunk loads. In order for the missile to land the other end needs to be chunk loaded. 

This can create some unexpected behavior as players were use to the old system of loading every area of the map between the target and the launcher. I removed this after 1.6.4 due to it stalling out larger servers. Specifically when players would chain fire missiles at another player and eventually crash a server due to it running out of RAM. 

The eventual goal is to attach our AA systems to this phased out map. This way missiles can be targeted and destroyed at distance before they land. Problem is I've been stuck on fixing performance issues with explosives and have yet to get to the new implementation.

**Comment by spartainman64** [comment]
But they never impact.
