### ISSUE TITLE
Please do not unload missiles at a certain height

### ISSUE THREAD

**Issue by KeiHasFallen** [BuiltBrokenModding/ICBM-Classic#357]
Please do not unload missiles at a specific height; I'd want the missile to go to the place so that we may intercept them with the anti-ballistic missile; if the missile unloads at a specific height, we will be unable to intercept them.

**Comment by GHXX** [comment]
as just mentioned in #320 , they despawn so we dont have to chunkload possibly thousands of chunks. Missiles will be unloaded.
In the future we may rework antiballistic missiles and the radar to account for that. We'll see. For now an EMP tower should work as a defense.

**Comment by DarkGuardsman** [comment]
Rework for missiles is planned to make them easier to attack. Unloading will not change as this is by design to prevent lagging out larger servers. 

Additionally even if we didn't unload them most missiles travel up to a high-y and come almost strait down. Only at short distance do they maintain an arc similar to artillery.
