### ISSUE TITLE
No Rejuvination?

### ISSUE THREAD

**Issue by Breadabix** [BuiltBrokenModding/ICBM-Classic#376]
Less of an issue and more of a question. Is there a reason Rejuvination wasnt added to 1.12, and is it likely to be added in the future? Thanks

**Comment by GHXX** [comment]
as far as i recall, rejuvenation was included in 1.12 at some point, but we decided to remove (or disable?) it as it didnt properly sync chunks to clients and we couldnt find a way to force a chunk-sync.
Another issue is that if you try to rejuvenate villages, then that doesnt work too well since it seems that cross-chunk structures still are spawned by a single chunk, so when rejuvenating 4 chunks that contains a house, you will likely not recreate the chunks in the correct order, thus you will end up with partial buildings. 

At this point, it might make a comeback at some point since it is a neat idea, but im not too certain.
Would definitely need to figure out a way to force-sync the chunks to the clients. (The structure gen not working is not too bad of a bug imo)

**Comment by Breadabix** [comment]
Thanks for the info, I imagine force-syncing chunks isnt as easy as it sounds just in text like this.

**Comment by GHXX** [comment]
According to what we tried it wasnt easy. If someone can think of a way, feel free to open a PR :)

**Comment by DarkGuardsman** [comment]
Its like it could have been fixed but it was always meant as an Admin utility. So when it became too time consuming to maintain it was dropped in favor of users installing others mods for the same feature.
