### ISSUE TITLE
[1.12] crash when editing explosive_reg.json file

### ISSUE THREAD

**Issue by Invisible229** [BuiltBrokenModding/ICBM-Classic#381]
configs invented to change them!!!! BUT when changing any one attribute leads to the original value of the attribute after starting the game, when changing more than 1 attribute leads to a crash!

**Comment by Invisible229** [comment]
I personally changed the "explosive_reg" config because I didn't like crafting very expensive but the explosion is very small, for example 8 stars from nather = several degrees ahead, so I set one to 50 = nuclear, 2 set to 250 , 3 set to 1000 and little things changed there except for them. After that, it began to fly out, that is, it crashes when entering..
[crash-2022-03-02_17.35.48-client.txt](https://github.com/BuiltBrokenModding/ICBM-Classic/files/8170265/crash-2022-03-02_17.35.48-client.txt)
.

**Comment by Invisible229** [comment]
please add updates to the list of files. Since some do not understand or do not know how to use the "source"

**Comment by GHXX** [comment]
You are not supposed to modify the explosive_reg.json file, as this file just maps explosive-names to ids.
The reason why it crashed during startup was because two of the explosive-names had the same id. 

If you want to change the mod's behaviour, only edit files that have the .cfg extension. Those files also include comments.

**Comment by DarkGuardsman** [comment]
@GHXX remind me later to move https://github.com/BuiltBrokenModding/ICBM-Classic/blob/6ec6ab695a0fadc4a6b14017c71dee042d43bb92/src/main/java/icbm/classic/ICBMClassic.java#L221 to the world folder. It will avoid people trying to mess with things that shouldn't be edited without good reason.

@Invisible229 making an issue saying "configs invented to change them" without having any clue what the file does is one of the worse ways to get help. Currently most of the explosives lack configs to edit scale. This is intentional as most explosives will run the server/client out of RAM trying to run at larger sizes.

**Comment by DarkGuardsman** [comment]
@GHXX  started https://github.com/BuiltBrokenModding/ICBM-Classic/wiki/Configs am on production support for day job so don't have time to finish it. If you have time or could motivate someone in the community to PR the rest of it.
