### ISSUE TITLE
Server Crash While Viewing Explosions

### ISSUE THREAD

**Issue by spruill7716** [BuiltBrokenModding/ICBM-Classic#399]
Using the latest alpha build, '_ICBM-classic-1.12.2-4.1.0b20211106011048_' and the latest release build produces this crash (on server) when any user is viewing an explosion. Very similar to #44 and #48 but fixes were published with those years back.

[https://www.dropbox.com/s/5skkx4nmqv29ph6/crash-2022-08-15_12.47.01-server.txt?dl=0](https://www.dropbox.com/s/5skkx4nmqv29ph6/crash-2022-08-15_12.47.01-server.txt?dl=0) 

There also seems to be an additional crash that mentions the 'Exotic Bird Mod' from ThePavoReality

[https://www.dropbox.com/s/gw78vmzwpq3016i/crash-2022-08-15_01.55.02-server.txt?dl=0](https://www.dropbox.com/s/gw78vmzwpq3016i/crash-2022-08-15_01.55.02-server.txt?dl=0)

**Comment by bl4ckscor3** [comment]
This is not caused by ICBM Classic. The error in question happens because SpongeForge tries to modify Minecraft's code using mixin, but failing since the code to modify does not exist in the form that is expected. ICBM Classic just triggers this, however other mods can, too. Try updating SpongeForge to at least 7.4.8-RC4139, there is a fix for a crash with a very similar error trace to this one.
