### ISSUE TITLE
[1.12] Task: Fix Redmatter BlackHole

### ISSUE THREAD

**Issue by Animeboy2003** [BuiltBrokenModding/ICBM-Classic#400]
The black hole created by Redmatter lasts forever and cannot be destroyed.

**Comment by DarkGuardsman** [comment]
Please open an issue with details instead of specifying a task. As tasks are for our own internal tracking on planned work.

That said the redmatter is working as expected. It has a very long decay that can result in it staying alive for days. As long as it continues to consume blocks or entities it will stay alive.
