### ISSUE TITLE
EMP

### ISSUE THREAD

**Issue by nerdman0** [BuiltBrokenModding/ICBM-Classic#403]
I was wondering, what does the EMP missile/bomb/minecraft/tower actually do? It destroys missiles (though it isn't working for one of the people on my discord) but what energy sources are affected currently?

**Comment by DarkGuardsman** [comment]
explosive version (missile, bomb, etc) should effect all blocks, items, and entities. This will include the missiles by having them destruct. 

As for the tower depending on the version it has modes to effect different types. Such as picking missiles only or tiles only. 

Along with this not all mods are supported due to limits of the Forge Energy System and Redstone Flux Energy System. So you may see some power content drain energy. While others are not effected. We attempted to solve this a while back by modifying the power system APIs. However, this was rejected both in forge and thermal expansion. Future plans will work around this by damaging machines and providing a config to control what happens per block.

If this is not working can you provide the version of the mod,  minecraft, and any related information.

**Comment by nerdman0** [comment]
so currently the energy part of the emp tower will do nothing, and the bomb will destroy energy blocks

**Comment by DarkGuardsman** [comment]
Testing with latest pre-release: Emp tower and bomb both work. Missiles are setup to not destroy but will instead turn of their engines. Meaning they still can fall and impact causing damage. 

Energy drain effect is working on limited tiles from testing. Block destroy mechanic is not yet implemented but will likely be in the next few releases.
