### ISSUE TITLE
A few questions.

### ISSUE THREAD

**Issue by User20230415** [BuiltBrokenModding/ICBM-Classic#411]
Well, first of all, why is there only 1 launcher now, why did you delete two more? I don't even know what to say, developer, why are you doing this? Why are you limiting our capabilities? Secondly, people should be able to control the scale of the explosion, you have made a configuration for the delay before the explosion, which seems somewhat useless in its essence. And don't say that there is no explosion control because "Currently most of the explosives lack configs to edit scale. This is intentional as most explosives will run the server/client out of RAM trying to run at larger sizes." is nonsense, it's equivalent to giving us a mod and then saying no you shouldn't use it. People should decide for themselves what and how to install them, depending on their needs and capabilities. In addition, no one has canceled the default configuration, just leave it as it is if you don't need to change anything. So it's just absurd when you worry about clients and servers without giving people the ability to control these functions. What I want to say is, well, don't take people for fools who are not in a state to just think and decide whether or not to change something.

**Comment by DarkGuardsman** [comment]
We have fewer launchers as we are moving away from tiers that didn't add gameplay experience. This isn't to limit options but to avoid wasting dev time maintaining 3 models and 3 different users experienced. Especially when the rewrite broke down the need for multi-blocks. Allowing a higher degree of customization of base builds. More launchers will be added to continue building on this experience. Such as multi-launcher cruise platforms and heavier launchers for cluster missiles once re-added.

Controllable scale is on the implementation list. It is a low priority feature due to how much time it takes to implement. A few of the larger explosives are already configurable such as antimatter. Can blame forge's lack of auto generated configs for this. As it means we have to manually add a config field per explosive. Then test to make sure it will not break any of old code. As most of the explosives are running 10 year old logic. Meaning they don't scale well and often fail to work at larger sizes. I could care less if it runs your server out of RAM because of poor admin choices. I do care if a user builds something and it doesn't work at all.

Finally, my issue tickets are not the place to rant about your interpretations of events.
