### ISSUE TITLE
Mobs Are Deleted Instead of Killed (5.3.0)

### ISSUE THREAD

**Issue by TFCAliarcy** [BuiltBrokenModding/ICBM-Classic#425]
When you land a direct hit on mobs that would be killed by a direct hit due to the missile doing enough damage to kill them such as chickens, cows, and other low health mobs it will kill them and they will do the normal things that happens when mobs die such as drop loot.

When you land a direct hit on a mob that has too much health to be killed by a direct hit such as a Wither (and modded mobs with high health such as Mutant Beasts or Ice&Fire Dragons) it will not kill it normally, instead it will deal the damage it is meant to then delete it leaving no drops or anything else that happens when a mob dies.

Note that the mobs dying due to splash damage acts normally and it isn't the explosion destroying loot since items are not destroyed by ICBM explosions.

**Comment by DarkGuardsman** [comment]
Strange, as we just apply normal damage on impact. Only thing I can think of is maybe something is crashing and preventing the game from closing by deleting the mob. Can you check your logs to see if anything shows up. I'll try to replicate it later but may not be able to find the time due to work.

Other possibility is the recent missile riding mechanic is failing. As you are able to cause entities to board missiles by shooting near them. I don't recall if it works for all mobs as it was added for chicken easter egg.

**Comment by TFCAliarcy** [comment]
[02:16:54] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Toby_Larone joined the game
[02:16:54] [Client thread/DEBUG] [FML]: Overriding dimension: using 0
[02:16:54] [Client thread/INFO] [net.minecraft.advancements.AdvancementList]: Loaded 41 advancements
[02:16:58] [Server thread/INFO] [icbmclassic]: Missile[4235] (1044x, 69y, -104z, 0d) impacted at (1046.1919492556412, 65.0, -103.93208436465883)
[02:16:58] [Server thread/INFO] [icbmclassic]: Explosion[icbmclassic:condensed] | Scale(x1.0) | BlastState(TRIGGERED) | EntitySource(4235) | Impacted (1,046.2x 65.0y -103.9z 0d)


This is what my debug log looks like when I tested it on a Wither and it doesn't look like anything is out of the ordinary.

**Comment by DarkGuardsman** [comment]
Ya that looks rather normal, still yet to check on my end but is sounding like the riding mechanic might be the source. As it looks like it triggered. My theory is that riding started and then the missile dies. Causing the rider to die with it.
