### ISSUE TITLE
Waila -> Incorrectly showing localizations

### ISSUE THREAD

**Issue by dmodoomsirius** [BuiltBrokenModding/ICBM-Classic#43]
Through Waila the locialized name is saying both support frame and launcher are Tier ones when they are not.

**Comment by DarkGuardsman** [comment]
Not seeing the issue, is this for the current version?

**Comment by Hennamann** [comment]
Just noticed what he is referring to, The launcher items are fine, the problem is with the actual block, Check them with waila installed and you'll notice two things: 
A: All the launchers say T1.
B: Parts of the multiblock are unlocalized.
Seems to me like it's metadata related, as Waila is pulling the same item icon for all of them.
Here are a few screenshots of the issue for reference:
![2017-02-25_20 55 20](https://cloud.githubusercontent.com/assets/7883761/23334372/08a70e8e-fb9d-11e6-9fb5-6d4ca523c83e.png)
![2017-02-25_20 56 58](https://cloud.githubusercontent.com/assets/7883761/23334362/f876ddfa-fb9c-11e6-94bd-5b92f1b3f91e.png)
![2017-02-25_20 57 03](https://cloud.githubusercontent.com/assets/7883761/23334365/fcc803e8-fb9c-11e6-8c04-b8c228ab2bf8.png)

**Comment by Hennamann** [comment]
This in Dev environment on the following commit: 7d7d61583d238260b0dc22711a4848a94ada082c

**Comment by DarkGuardsman** [comment]
Oh so its the tooltips that are broken not the inventory items or placed items. I can fix this shortly TY

**Comment by DarkGuardsman** [comment]
Ok, just went to look at it to see what needed fixed. Still not seeing the issue and everything reads correctly. Do you have waila installed? As the NEI version works perfect on my dev environment.

**Comment by Hennamann** [comment]
Yup, got waila installed manually in the mods folder. and nei is running as a dependency in IDEA. i can test it again if you'd like?

**Comment by DarkGuardsman** [comment]
Try without waila, it might be reading data incorrectly. If that is the case I need to add support for waila.

**Comment by Hennamann** [comment]
Yes, the issue is specific to waila, seemingly it loads the localization wrong. The normal items are fine, even in NEI. Though judging from the unlocalized parts of the launchers saying "tile.veMultiblock.name" I would imagine that this issue has roots with VE and not just ICBM-Classic.

**Comment by DarkGuardsman** [comment]
Multi-blocks have no translation as the player should never have the block. The block also has code to redirect localizations to the core block. It seems waila is doing something different and has caused the issue. Luckily, this is easy to fix by just adding waila support to the project.
