### ISSUE TITLE
Updating Trinity ICBM integration from version 5.x to 6.x

### ISSUE THREAD

**Issue by tomdodd4598** [BuiltBrokenModding/ICBM-Classic#441]
Hey there! Trinity now has a [public repository](https://github.com/igentuman/NC-Trinity) and I've been working on getting it updated to the latest versions of NCO and ICBM. At the moment, it is stable against version 5.4.0, but I am now trying to update to 6.2.0.

There only seems to be a couple of problems. Firstly, and more importantly, Trinity used the `BlastEMP` class in a couple of places to build and run some EMP explosions, which now seems to be gone. Secondly, the `IExplosiveData` interface has been deprecated, as has the `Blast` class. Is it still okay to use these, or will they eventually be removed? For example, Trinity uses `Blast::getActionData` and `IExplosiveData::getTier` in a few places.

**Comment by DarkGuardsman** [comment]
Tier is going away, it has no usage other than for user visuals and some internal content generation.

IExplosiveData is being replaced with IActionData. Its still fine to use in 1.12 but I'm removing it after I finish porting to newer versions. Goal is to get everything to a generic system. This way logic feeds through similar mechanics without needing specialized systems. Since before this I was ending up with IExplosiveData, IProjectileData, ITriggerData... when all 3 are just actions with different world outputs.

For your usage, there is an action for EMPs. Can look at the EMPTower for implementation details. This code shouldn't roughly stay the same. With the only planned change to split EMP into small actions to better support specific mods.

**Comment by tomdodd4598** [comment]
Cheers! All looks good now :)
