### ISSUE TITLE
bug... i think

### ISSUE THREAD

**Issue by erilun06** [BuiltBrokenModding/ICBM-Classic#51]
https://paste.ee/p/2vyYl

help, please!

it worked this morning

**Comment by dmodoomsirius** [comment]
please go to C:\Users\elev\Desktop\MultiMC\instances\1.7.10\minecraft\hs_err_pid9768.log and upload that to a pastebin like website like you did for the log file and please link that to us.

Thanks

**Comment by erilun06** [comment]
here it is
https://paste.ee/p/2ioDN

**Comment by DarkGuardsman** [comment]
Taking a look at the second log all I see to work with that is not Minecraft vanilla code is

bspkrs.client.util.EntityUtils.drawEntityOnScreen(IIFFFLnet/minecraft/entity/EntityLivingBase;)V+237
j  bspkrs.bspkrscore.fml.BSMainMenuRenderTicker.onTick(Lcpw/mods/fml/common/gameevent/TickEvent$RenderTickEvent;)V+299

This is most likely not the cause but these types of crashes are hard to narrow down. The only option to work with at the moment is to test a few mods at a time. Then see if the issue continues.

Additionally what made you think that issue was related to ICBM-Classic?

**Comment by erilun06** [comment]
these lines


[20:50:00] [Client thread/WARN]: File flansmod:sounds/BulletHit.ogg does not exist, cannot add it to event flansmod:BulletHit
[20:50:00] [Client thread/WARN]: File icbmclassic:sounds/laser1.ogg does not exist, cannot add it to event icbmclassic:laser

**Comment by DarkGuardsman** [comment]
That just a missing audio file, plus as you can see flans is missing one as well.

additionally, if you read the log flans errors out a good bit for unrelated issues.

**Comment by erilun06** [comment]
it was the only red text I could find

**Comment by DarkGuardsman** [comment]
Sadly not all errors show as red text due to how some developers write their code. Which can make it harder and more confusing to find the issue. That being said I did read over the log and saw nothing point at the problem directly. All of the issues are unrelated or like the audio line can be ignored. From what I can tell the issue is render related but the crash does not point at the source. Looking at Minecraft's code the likely spot is when its setting the texture state. Though this doesn't make much sense but I do have a few things we can test.

0) Test on a new empty world
1) Reset your graphics settings on Minecraft
2) If you using mods like FastCraft and optifine. Try running without
3) Run with just BBM mods (ICBM, VoltzEngine, ICBM-Sentries, and so on)
4) Run without flans, it has a lot of errors in that log
5) Check your graphics card settings, ensure its updated, and not manually setting Minecraft's settings. This has been known to cause issues from mouse problems to render crashes. Google how to do this as it is different per brand and model of graphics card.

**Comment by erilun06** [comment]
I changed to curse /twitch/Microsoft's launcher and it worked
