### ISSUE TITLE
EMP not draining power?

### ISSUE THREAD

**Issue by Breadabix** [BuiltBrokenModding/ICBM-Classic#69]
I have been testing the mod for bugs and server crashing features/items, and the EMP explosive, missile and tower dont drain power from anything, except TE energy cells when placed. The mods I have tested are as follows: 
ThermalExpansion-[1.7.10]4.1.5-248
RedstoneArmory-1.7.10-1.2.0-41
RedstoneArsenal-[1.7.10]1.1.3-97
BigReactors-0.4.3A
Mekanism-1.7.10-8.1.9.265 (with generators/tools of the same version)
EnderIO-1.7.10-2.3.0.429_beta
SimplyJetpacks-MC1.7.10-1.5.3
Mffs-1.7.10-0.0.51b144
Draconic-Evolution-1.7.10-1.0.2h
ModularPowersuits-1.7.10-0.11.1.114
ThermalRecycling-1.7.10-1.1.0.5
Ex-Astris-MC1.7.10-1.16-36
RFDrills-1.7.10-1.7.3
WirelessCraftingTerminal-1.7.10-rv3-1.8.7.4b
appliedenergistics2-rv3-beta-6
ExtraPlanets-1.8.1
GalacticraftCore-1.7-3.0.12.501
GraviSuite-1.7.10-2.0.3
industrialcraft-2-2.2.827-experimental
QuantumFlux-1.7.10-1.3.4
ExtraCells-1.7.10-2.3.14b197

Is there any possibility of a fix for this? I am using ICBM-classic-1.7.10-2.15.1b184, the latest version released at the time of testing

**Comment by DarkGuardsman** [comment]
RF and IC2 support are not built up very well for the mod at the moment. Especially with RF API being designed to prevent a massive drain of energy. The issue is being worked on with a new version of the EMP being implemented in the core VoltzEngine. Once this is done the code will be updated for ICBM-Classic to use the same EMP as ICBM.

**Comment by Breadabix** [comment]
Thanks. From what I understand of that im assuming it may be a while before this is fixed entirely?

**Comment by DarkGuardsman** [comment]
Depends, I have to get the EMP ported soon this week for another project. So the new version will be done but it might be a bit longer for RF & IC2 support to be fixed. Both take a while to test and I will need to make special handling for some mods. Especially those that use RF since its API is not designed to remove all energy in one go. The author of Thermal Expansion has already told me he doesn't want it to behave that way as well. Though I still plan to make it work no matter what.

**Comment by Breadabix** [comment]
Good luck then, especially with Thermal Expansion :)

**Comment by Breadabix** [comment]
I have just tested this with the newest release and can say the energy cube and induction cell from mekanism, cell from thermal expansion and MFSU from IC2 are being emptied when placed, however nothing is emptied within the inventory.

**Comment by DarkGuardsman** [comment]
Inventory support has not been added but other than that, good to hear :)

**Comment by Breadabix** [comment]
Do you know when inventory support is being implemented, or is it just one of those things thats going to be added whenever there is time available?

**Comment by DarkGuardsman** [comment]
Not sure when it will be added, it's not a high priority as the main purpose of an EMP is to kill machines. I guess I could work on it this week but free time is low right now.

**Comment by Breadabix** [comment]
EMPs do not seem to be emptying fortron out of mffs machines, I dont know if this is meant to happen or not

**Comment by DarkGuardsman** [comment]
It's been a while since I've worked on the MFFS code. If I recall right it was waiting on the EMP API which was only added a little while ago. This way the EMP would effect the shield blocks and not just the machines.... honestly I need to work on MFFS again lol.

**Comment by Breadabix** [comment]
Newest version not empying placed Mekanism things, along with anything in inventory and MFFS.

**Comment by Breadabix** [comment]
Just tested latest 1.7.10 version with TE, Mekanism and IC2 and the EMP only emptied the TE energy cell
